"""catalog tables

Revision ID: 0c3b045a0de4
Revises: 2675862b84a7
Create Date: 2026-07-15 11:25:04.048307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3b045a0de4'
down_revision: Union[str, Sequence[str], None] = '2675862b84a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_code_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_key', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name_cn', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_key', 'code', name='uq_codedict_table_code')
    )
    op.create_table('data_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tds_code', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('provider_connector_id', sa.String(length=36), nullable=False),
    sa.Column('kuscia_domain_id', sa.String(length=63), nullable=False),
    sa.Column('kuscia_domaindata_id', sa.String(length=63), nullable=True),
    sa.Column('resource_category', sa.String(length=8), nullable=True),
    sa.Column('source_type', sa.String(length=8), nullable=True),
    sa.Column('delivery_form', sa.String(length=8), nullable=True),
    sa.Column('update_freq', sa.String(length=8), nullable=True),
    sa.Column('quality_level', sa.String(length=4), nullable=True),
    sa.Column('security_level', sa.String(length=4), nullable=False),
    sa.Column('service_type', sa.String(length=8), nullable=True),
    sa.Column('topic_category', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('relative_uri', sa.String(length=512), nullable=True),
    sa.Column('datasource_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tds_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_catalog')
    op.drop_table('catalog_code_dict')
    # ### end Alembic commands ###
