"""connector table

Revision ID: 2675862b84a7
Revises: 
Create Date: 2026-07-15 10:00:34.719060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2675862b84a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tds_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('kuscia_domain_id', sa.String(length=63), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kuscia_domain_id'),
    sa.UniqueConstraint('tds_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connector')
    # ### end Alembic commands ###
