"""catalog datasource and data_type

Revision ID: 3ddc05708b55
Revises: 1c2ed60d5554
Create Date: 2026-07-15 19:16:34.877939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddc05708b55'
down_revision: Union[str, Sequence[str], None] = '1c2ed60d5554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('kuscia_domain_id', sa.String(length=63), nullable=False),
    sa.Column('kuscia_datasource_id', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.String(length=512), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # 存量行回填默认 'table'（结构化）
    op.add_column('data_catalog', sa.Column('data_type', sa.String(length=16), nullable=False, server_default='table'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_catalog', 'data_type')
    op.drop_table('data_source')
    # ### end Alembic commands ###
