"""appimage job template

Revision ID: 3def34fd858d
Revises: 59b85e22a7de
Create Date: 2026-07-16 14:19:13.682483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3def34fd858d'
down_revision: Union[str, Sequence[str], None] = '59b85e22a7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_image', sa.Column('job_template', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_image', 'job_template')
    # ### end Alembic commands ###
