"""usage lifecycle

Revision ID: 59b85e22a7de
Revises: c9c010baab98
Create Date: 2026-07-16 13:20:11.489166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b85e22a7de'
down_revision: Union[str, Sequence[str], None] = 'c9c010baab98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('usage_record_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_job_usage_record_id'), 'job', ['usage_record_id'], unique=False)
    op.add_column('usage_counter', sa.Column('reserved_count', sa.Integer(), nullable=False))
    op.add_column('usage_record', sa.Column('lifecycle', sa.String(length=16), nullable=False))
    op.add_column('usage_record', sa.Column('job_id', sa.String(length=36), nullable=True))
    op.add_column('usage_record', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_usage_record_job_id'), 'usage_record', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_record_job_id'), table_name='usage_record')
    op.drop_column('usage_record', 'updated_at')
    op.drop_column('usage_record', 'job_id')
    op.drop_column('usage_record', 'lifecycle')
    op.drop_column('usage_counter', 'reserved_count')
    op.drop_index(op.f('ix_job_usage_record_id'), table_name='job')
    op.drop_column('job', 'usage_record_id')
    # ### end Alembic commands ###
