"""job

Revision ID: 95f995e60f98
Revises: ab9f2cceff8d
Create Date: 2026-07-15 19:58:35.624875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f995e60f98'
down_revision: Union[str, Sequence[str], None] = 'ab9f2cceff8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=47), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('app_image', sa.String(length=128), nullable=False),
    sa.Column('initiator_connector_id', sa.String(length=36), nullable=False),
    sa.Column('initiator_domain', sa.String(length=63), nullable=False),
    sa.Column('provider_connector_id', sa.String(length=36), nullable=False),
    sa.Column('provider_domain', sa.String(length=63), nullable=False),
    sa.Column('consumer_connector_id', sa.String(length=36), nullable=False),
    sa.Column('consumer_domain', sa.String(length=63), nullable=False),
    sa.Column('input_provider_domaindata_id', sa.String(length=63), nullable=False),
    sa.Column('input_consumer_domaindata_id', sa.String(length=63), nullable=False),
    sa.Column('kuscia_job_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_domaindata_id', sa.String(length=63), nullable=True),
    sa.Column('result_uri', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
