"""appimage and product allowed_appimages

Revision ID: ab9f2cceff8d
Revises: 3ddc05708b55
Create Date: 2026-07-15 19:38:16.814496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9f2cceff8d'
down_revision: Union[str, Sequence[str], None] = '3ddc05708b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('image_name', sa.String(length=512), nullable=False),
    sa.Column('image_tag', sa.String(length=128), nullable=False),
    sa.Column('deploy_templates', sa.JSON(), nullable=True),
    sa.Column('config_templates', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('data_product', sa.Column('allowed_appimages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_product', 'allowed_appimages')
    op.drop_table('app_image')
    # ### end Alembic commands ###
