"""product and contract

Revision ID: c99146257a06
Revises: 0c3b045a0de4
Create Date: 2026-07-15 13:31:40.311510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99146257a06'
down_revision: Union[str, Sequence[str], None] = '0c3b045a0de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tds_code', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('provider_connector_id', sa.String(length=36), nullable=False),
    sa.Column('kuscia_domain_id', sa.String(length=63), nullable=False),
    sa.Column('transaction_mode', sa.String(length=16), nullable=False),
    sa.Column('baseline_policies', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tds_code')
    )
    op.create_table('digital_contract',
    sa.Column('contract_id', sa.String(length=47), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('provider_connector_id', sa.String(length=36), nullable=False),
    sa.Column('consumer_connector_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('contract_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('contract_party',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=47), nullable=False),
    sa.Column('party_role', sa.String(length=16), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('signature_hash', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['digital_contract.contract_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=47), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=16), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('curr_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['digital_contract.contract_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negotiation_history')
    op.drop_table('contract_party')
    op.drop_table('digital_contract')
    op.drop_table('data_product')
    # ### end Alembic commands ###
