"""usage control

Revision ID: c9c010baab98
Revises: 95f995e60f98
Create Date: 2026-07-16 13:08:13.546633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c010baab98'
down_revision: Union[str, Sequence[str], None] = '95f995e60f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_counter',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=47), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'action')
    )
    op.create_index(op.f('ix_usage_counter_contract_id'), 'usage_counter', ['contract_id'], unique=False)
    op.create_table('usage_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=47), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('matched_policy_ids', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_record_contract_id'), 'usage_record', ['contract_id'], unique=False)
    op.create_index(op.f('ix_usage_record_request_id'), 'usage_record', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_record_request_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_contract_id'), table_name='usage_record')
    op.drop_table('usage_record')
    op.drop_index(op.f('ix_usage_counter_contract_id'), table_name='usage_counter')
    op.drop_table('usage_counter')
    # ### end Alembic commands ###
