"""appimage registry source

Revision ID: e5a51d6c816b
Revises: 3def34fd858d
Create Date: 2026-07-20 14:17:29.253266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a51d6c816b'
down_revision: Union[str, Sequence[str], None] = '3def34fd858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_image', sa.Column('registry_source', sa.String(length=16), server_default='third_party', nullable=False))
    op.add_column('app_image', sa.Column('registry', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_image', 'registry')
    op.drop_column('app_image', 'registry_source')
    # ### end Alembic commands ###
